<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Facebook helps you connect and share wi_41e91d</name>
   <tag></tag>
   <elementGuidId>f10d867a-2241-4f21-939e-d7eb5d4f36a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fb_logo._8ilh.img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Facebook&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>435d4204-c089-47d1-93ff-867f1aec499b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fb_logo _8ilh img</value>
      <webElementGuid>e8368496-6b08-4311-b829-e03af9b9ee25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg</value>
      <webElementGuid>90320b8d-f7f6-4d81-b426-8d19a681b456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Facebook</value>
      <webElementGuid>e2301b2b-35e2-4910-a20e-30a6e2bff077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[1]/div[@class=&quot;_8esj _95k9 _8esf _8opv _8f3m _8ilg _8icx _8op_ _95ka&quot;]/div[@class=&quot;_8esk&quot;]/div[@class=&quot;_8esl&quot;]/div[@class=&quot;_8ice&quot;]/img[@class=&quot;fb_logo _8ilh img&quot;]</value>
      <webElementGuid>bc25c8a0-cd4d-4977-b095-ad26ecf97373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/div/img</value>
      <webElementGuid>06218611-5033-4d0f-a00a-74680347ed2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Facebook']</value>
      <webElementGuid>66821f37-f2e9-4ccd-83d2-29bce5cf30ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>40ce9565-1361-4fb1-a59e-d2b505b67a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.xx.fbcdn.net/rsrc.php/y1/r/4lCu2zih0ca.svg' and @alt = 'Facebook']</value>
      <webElementGuid>3a24a373-fca9-4d05-b439-19cd5c6b648d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
